apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-2
  labels:
    app: test-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-2
  template:
    metadata:
      labels:
        app: test-2
    spec:
      containers:
        - name: test-2
          image: eub456/test:latest
          ports:
            - containerPort: 80
